/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MiningResult {
  duration: number
  gasPrice: string
}
export interface MiningConfig {
  batchSize?: number
  threadCount?: number
}
export declare class GasMiner {
  constructor()
  getCpuCount(): number
  mineGasForTransaction(nonce: number, gas: number, from: string, config?: MiningConfig | undefined | null): Promise<MiningResult>
}
